name: Generate Sitemap

on:
  push:
    branches:
      - main   # غيّرها إذا كان فرعك غير main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate sitemap.xml
        run: node sitemap-generator.js

      - name: Commit and push sitemap.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap.xml" || echo "No changes to commit"
          git push
